# Generated by Django 4.2.5 on 2023-11-18 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_listing_highest_bidder_alter_listing_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="current_bidding",
            new_name="current_highest_bid",
        ),
    ]
