# Generated by Django 4.2.5 on 2023-11-21 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_userprofile_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="watchlist",
        ),
    ]
