# Generated by Django 4.2.5 on 2023-11-21 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_watchlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
