# Generated by Django 4.2.5 on 2023-11-21 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auctions", "0009_watchlist"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "listing")},
        ),
    ]
