# Generated by Django 4.2.5 on 2023-11-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_watchlist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="is_winning_bid",
            field=models.BooleanField(default=False),
        ),
    ]
